#!/bin/bash

# @author Ayush Sharma

function checkString() {
	if [[ $1 =~ ^[A-Za-z]+$ ]]
	then
		isAllLetters=0
	else
		isAllLetters=1
	fi
}

function threeLetters() {
	if [[ ${#1} == 3 ]]
	then
		isLengthThree=0
	else
		isLengthThree=1
	fi
}

function properLogin() {
	checkString $1
	threeLetters $1
	if [[ ( $isAllLetters == 1 ) || ( $isLengthThree == 1 ) ]]
	then
		isProperLogin=1
	else
		isProperLogin=0
	fi
}

if [ $1 ]
then
	user=$1
else
	echo "What's your CS61C 3-letter login (cs61c-xxx)?"
	read user
fi

properLogin $user
if [[ $isProperLogin == 1 ]]
then
	echo "Please enter a 3-letter login."
	exit 1
fi

echo "Login $user received, attempting to connect..."

: '
Please fill out the below line, filling in the following:
	a) The command you use to execute Python (e.g., python3, py, python)
	b) The path to your telepath.py file
'
telepathOut=$(python3/py/python your/path/to/telepath.py)
ssh cs61c-$user@hive$telepathOut.cs.berkeley.edu
